CREATE TABLE "products_complete" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "products_complete_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"org_id" integer NOT NULL,
	"nickname" varchar(255) NOT NULL,
	"description" text,
	"epa_number" varchar(50),
	"manufacturer" varchar(255),
	"product_type" varchar(50),
	"chemical_type" varchar(50),
	"category" varchar(100),
	"status" varchar(20) DEFAULT 'active',
	"default_applied_input" numeric(10, 4),
	"default_unit_applied" varchar(20),
	"base_unit" varchar(20),
	"application_rate_per_acre" numeric(10, 4),
	"field_application_price" numeric(10, 2),
	"minimum_charge" numeric(10, 2),
	"commission" varchar(50),
	"commission_paid" numeric(10, 4),
	"extra_commission_percent" numeric(5, 2),
	"unit_cost" numeric(10, 2),
	"reorder_qty" numeric(10, 4),
	"vendors" text,
	"otc_chemical_sale_price" numeric(10, 2),
	"density_conversion_rate" numeric(10, 6),
	"density_unit_from" varchar(20),
	"density_unit_to" varchar(20),
	"is_restricted" boolean DEFAULT false,
	"dont_split_billing" boolean DEFAULT false,
	"is_inventory_item" boolean DEFAULT false,
	"is_discountable" boolean DEFAULT false,
	"show_on_job_schedule" boolean DEFAULT false,
	"is_diluent" boolean DEFAULT false,
	"apply_as_liquid" boolean DEFAULT false,
	"label_signal_word" varchar(20),
	"hours_reentry" numeric(10, 2),
	"days_preharvest" numeric(10, 2),
	"crop_overrides" json,
	"sensitive_crops" json,
	"reentry_ppe" text,
	"additional_restrictions" text,
	"active_ingredients" text,
	"extracted_from_screenshot" boolean DEFAULT false,
	"screenshot_url" text,
	"extraction_confidence" numeric(3, 2),
	"last_verified_at" timestamp,
	"last_verified_by" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by" integer
);
--> statement-breakpoint
ALTER TABLE "products_complete" ADD CONSTRAINT "products_complete_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products_complete" ADD CONSTRAINT "products_complete_last_verified_by_users_id_fk" FOREIGN KEY ("last_verified_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products_complete" ADD CONSTRAINT "products_complete_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;